# Generated by Django 6.0.3 on 2026-03-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MED', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
