# Generated by Django 6.0.3 on 2026-03-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MED', '0004_medicine_worker_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MED.worker'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='worker',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('Pharmacist', 'Pharmacist'), ('Rider', 'Rider'), ('Manager', 'Manager')], default='Pharmacist', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
